### ISSUE TITLE
GC content theoretical distribution for plant

### ISSUE THREAD

**Issue by CharlotteSai** [UofABioinformaticsHub/ngsReports#16]
Hi All,

Firstly I have to say thank you all for creating this handy tool. It helped me a lot as it is informative and time-saving. 

I had an issue with the GC content theoretical distribution here. I am working on plants, Arabidopsis and barley mostly, but the GC content theoretical distribution is not available for plants. I am hoping this can be considered.

Cheers,
Charlotte

**Comment by tothuhien** [comment]
Hi Charlotte, for now theoretical GC content in this package are based on available genomes and transcriptomes R data package. So you can find GC content of Arabidopsis genome but not transcriptome here; barley is not available neither. But we could generate them as long as we have transcriptome sequences. Do you have any preferred data resource for Arobidopsis and Barley (ncbi or some specific database resource)? 
@steveped Do you think we'll include that in the package ?

**Comment by CharlotteSai** [comment]
Hi Hien,

Thanks for your quick reply. 
For Arabidopsis, we usually pull out information directly from the TAIR website.

Cheers,
Charlotte

**Comment by tothuhien** [comment]
Thanks Charlotte, I've found the transcript sequences for Arabidopsis.

Hi Steve, I'm just wondering whether we'll include that in the default theoretical GC content data, or should we add in the shiny-app a button allowing users to upload their own fasta sequences and generate the theoretical GC content for themselves? Or we can do both of them?
Thanks,

Hien

**Comment by steveped** [comment]
Hi all. If we can get the info into the main object that'd be great. Are you able to do this & make a pull request Hien? Chris & I have been slamming improvements into the `addFuns` branch ready to resubmit the paper too, so it may be nice to just have this in a separate branch. That way we can merge into `master` & push to the current release version.

**Comment by CharlotteSai** [comment]
Hi all, 

Thanks for solving my issue. Looking forward to the new version release.

Cheers,
Charlotte

**Comment by steveped** [comment]
Hi @CharlotteSai & @tothuhien .
I've added the Transcriptomic GC content to the default `gcTheoretical` object now & this is in both the `master` and `RELEASE_3_9` branches. I've also pushed this addition to Bioconductor, so this will be available from the main repo within the next few days.
Steve
