### ISSUE TITLE
Error in .makeLabels()

### ISSUE THREAD

**Issue by edgardomortiz** [UofABioinformaticsHub/ngsReports#22]
Hello, I got the following error:

```
Error in .makeLabels(df, labels, ...) : Labels must be unique.
```

After investigating I realized is caused by parts of the filename (e.g. `Psammisia-coarctata_EO2278_R1.fq.gz`) that contains the `sam` pattern searched by the function `.makeLabels()`:

https://github.com/UofABioinformaticsHub/ngsReports/blob/dc20c8e158ec3e63197b709c912ee732c8ab16a0/R/helpers.R#L163

Perhaps escaping the periods will detect the file extension? I am not sure how regex works in R:

```
    df, labels, pattern = "\.(fastq|fq|bam|sam|cram)\..*", col ="Filename", ...){
```

Edgardo

**Comment by steveped** [comment]
Hi @edgardomortiz ,

Thanks for pointing this out! We do need to be more explicit about our default patterns so I will change this in time for the April BioC release. In the meantime, if you provide a named vector to the `labels` argument, you should be able to sidestep this issue. Let me know if that's not a viable workaround & I'll try get the patch/testing done sooner.

Cheers,

Steve

**Comment by edgardomortiz** [comment]
Thanks @steveped , the named vector method worked! (as an R novice I never created a named vector before)

Edgardo

**Comment by steveped** [comment]
Great. I'm pleased to hear that got you moving again. I'll have a look at improving the documentation too so that's clearer to anyone else that comes across this issue. All the best with everything & thanks for raising this too.
