### ISSUE TITLE
error in writeHtmlReport

### ISSUE THREAD

**Issue by tothuhien** [UofABioinformaticsHub/ngsReports#6]
I've just tried to generate the report using _writeHtmlReport_ function, but it was stopped by an error:
Error in arrange_impl(.data, dots) : 
  Evaluation error: object 'Percentage' not found.
I was in the _Kmer_content_ chunk code, the object _kc_ doesn't have field Percentage

**Comment by steveped** [comment]
Thanks Hien. I think it was a namespace issue for `arrange()`. I've updated now by adding the `dplyr::` namespace. Can you let me know if that's fixed it? If not, are you able to email me the fastqc files?

**Comment by tothuhien** [comment]
I've updated the package and run again but had the same error. I just run the first chunk in the vignette (which was not evaluated)
_fileDir <- system.file("extdata", package = "ngsReports")_
_writeHtmlReport(fileDir)_

**Comment by tothuhien** [comment]
Thanks Steve, that works now.
