### ISSUE TITLE
error on import

### ISSUE THREAD

**Issue by JulianSpagnuolo** [UofABioinformaticsHub/ngsReports#7]
I am processing some DropSeq sequencing files, one of the fastqc outputs (from Read 1) cannot be read by the getFastqcData function. However, the report from Read 2 fastq.gz can be read without issue.

``` {r}
r1.fqc <- getFastqcData(list.files(path = "~/dropseq/DSmix0801/fastq/", pattern = "DSmix0801_S1_L001_R1_001_fastqc.zip$", full.names = TRUE))
```

Error in dimnames(x) <- dn : length of 'dimnames' [2] not equal to array extent

**Comment by steveped** [comment]
Hi Julian. That sounds like it might be a problem in a lower-level function we must be using as we don't have any calls to `dimnames()`. Can you please [email me](mailto:stephen.pederson@adelaide.edu.au) the file and I'll have a look?
